import axios from 'axios';
import { authStorage } from '../auth/authStorage'; 
import { http } from './http';

const API_BASE_URL = import.meta.env.VITE_API_URL;

export const listService = {
    // Obtener todas las listas del usuario
    getUserLists: async () => {
        const response = await http.get('/lists');
        return response.data;
    },

    // Crear una nueva lista
    createList: async (name, is_public = true) => {
        const response = await http.post('/lists', { name, is_public });
        return response.data;
    },

    // Agregar una película a una lista específica
    addMovieToList: async (listId, movieData) => {
        const response = await http.post(`/lists/${listId}/add-movie`, movieData);
        return response.data;
    },

    // Eliminar una película de una lista específica
    deleteList: async (id) => {
        const response = await http.delete(`/lists/${id}`);
        return response.data;
    },

    // Traer los datos de una lista específica
    getListDetails: async (id) => {
        const response = await http.get(`/lists/${id}`);
        return response.data;
    },

    // Actualizar nombre y privacidad
    updateList: async (id, name, is_public) => {
        const response = await http.put(`/lists/${id}`, { name, is_public });
        return response.data;
    },

    // Eliminar una película de una lista específica
    removeMovieFromList: async (listId, movieId) => {
        const response = await http.delete(`/lists/${listId}/remove-movie`, {
            data: { movie_id: movieId } 
        });
        return response.data;
    },

    getAllPublicLists: async () => {
        try {
            const response = await http.get('/lists/public');
            return response.data;
        } catch (error) {
            console.error("Error al obtener listas públicas:", error);
            return [];
        }
    },

    getAutoGeneratedLists: async () => {
       const categories = [
            { 
                id: 'trending', 
                name: 'Tendencias', 
                query: 'trending', // Buscamos por año para que salgan cosas actuales
                desc: 'Lo más visto y comentado de este año.' 
            },
            { 
                id: 'popular', 
                name: 'Favoritas del Público', 
                query: 'Avengers', // Una palabra clave potente para pelis famosas
                desc: 'Los grandes éxitos que todo el mundo conoce.' 
            },
            { 
                id: 'horror', 
                name: 'Terror Prohibido', 
                query: 'Terror', 
                desc: 'Una selección de pesadilla para no dormir.' 
            }
        ];

        try {
            const enriched = await Promise.all(categories.map(async (cat) => {
                let movies = [];
                // Usamos los métodos de movieService que ya funcionan
                if (cat.id === 'trending') movies = await movieService.getTrending();
                if (cat.id === 'popular') movies = await movieService.getPopular();
                if (cat.id === 'horror') movies = await movieService.getMoviesByGenre(27);

                const slice = (movies || []).slice(0, 3);
                return {
                    ...cat,
                    // CORRECCIÓN: m.poster_path ya es una URL completa gracias a movieService
                    posters: slice.map(m => m.poster_path || '')
                };
            }));
            return enriched;
        } catch (error) {
            console.error("Error en sugerencias API:", error);
            return categories.map(c => ({ ...c, posters: [] }));
        }
    },
};