import axios from 'axios';
import { authStorage } from '../auth/authStorage'; 
import { http } from './http';
import { movieService } from './movieService';

const API_BASE_URL = import.meta.env.VITE_API_URL;

export const listService = {
    // Obtener todas las listas del usuario
    getUserLists: async () => {
        const response = await http.get('/lists');
        return response.data;
    },

    // Crear una nueva lista
    createList: async (name, is_public = true) => {
        const response = await http.post('/lists', { name, is_public });
        return response.data;
    },

    // Agregar una película a una lista específica
    addMovieToList: async (listId, movieData) => {
        const response = await http.post(`/lists/${listId}/add-movie`, movieData);
        return response.data;
    },

    // Eliminar una película de una lista específica
    deleteList: async (id) => {
        const response = await http.delete(`/lists/${id}`);
        return response.data;
    },

    // Traer los datos de una lista específica
    getListDetails: async (id) => {
        const response = await http.get(`/lists/${id}`);
        return response.data;
    },

    // Actualizar nombre y privacidad
    updateList: async (id, name, is_public) => {
        const response = await http.put(`/lists/${id}`, { name, is_public });
        return response.data;
    },

    // Eliminar una película de una lista específica
    removeMovieFromList: async (listId, movieId) => {
        const response = await http.delete(`/lists/${listId}/remove-movie`, {
            data: { movie_id: movieId } 
        });
        return response.data;
    },

    // Obtener todas las listas públicas
    getAllPublicLists: async () => {
        try {
            const response = await http.get('/lists/public');
            return response.data;
        } catch (error) {
            console.error("Error al obtener listas públicas:", error);
            return [];
        }
    },

    // Obtener las listas autogeneradas
    getAutoGeneratedLists: async () => {
        const categories = [
            { 
                id: 'hits', 
                name: 'Éxitos de Taquilla', 
                query: 'Action',
                desc: 'Las películas más famosas y vistas de la plataforma.', 
                 fetch: () => movieService.getMoviesByGenre(28) 
            },
            { 
                id: 'top', 
                name: 'Joyas del Cine', 
                query: 'Top', 
                desc: 'Obras maestras con las mejores puntuaciones de la historia.', 
                fetch: movieService.getTopRated 
            },
            { 
                id: 'horror', 
                name: 'Terror Imprescindible', 
                query: 'Terror', 
                desc: 'Una selección de pesadilla con lo mejor del género.', 
                fetch: () => movieService.getMoviesByGenre(27) 
            }
        ];

        try {
            return await Promise.all(categories.map(async (cat) => {
                const movies = await cat.fetch();
                const limited = (movies || []).slice(0, 20); 
                return {
                    ...cat,
                    movieCount: limited.length,
                    posters: limited.slice(0, 5).map(m => m.poster_path || '')
                };
            }));
        } catch (error) {
            console.error("Error en sugerencias:", error);
            return [];
        }
    }
};