import React, { useEffect, useState } from 'react';
import { listService } from '../services/listService';
import { useAuth } from '../auth/authContext';
import LoadingAnimation from '../components/LoadingAnimation';
import ListCard from '../components/ListCard'; // Importamos tu componente
import './ListsPage.css';
import { useNavigate } from 'react-router-dom';

const ListsPage = () => {
    const { user } = useAuth();
    const navigate = useNavigate();
    const [communityLists, setCommunityLists] = useState([]);
    const [myLists, setMyLists] = useState([]);
    const [suggestedLists, setSuggestedLists] = useState([]); 
    const [loading, setLoading] = useState(true);

    const fetchAllLists = async () => {
        setLoading(true);
        try {
            // 1. Definimos las promesas básicas (públicas y sugerencias)
            const promises = [
                listService.getAllPublicLists(),
                listService.getAutoGeneratedLists()
            ];

            // 2. Si el usuario está logueado, pedimos todas sus listas (incluye las privadas)
            if (user) {
                promises.push(listService.getUserLists());
            }

            const results = await Promise.all(promises);
            const publicData = results[0];
            const autoData = results[1];
            const userData = results[2] || []; // Listas personales del usuario

            setSuggestedLists(autoData);

            if (user) {
                // "Tus Listas" ahora usa los datos de getUserLists (incluye privadas)
                setMyLists(userData);
                
                // "Comunidad" filtra las listas públicas para no mostrar las tuyas
                setCommunityLists(publicData.filter(l => l.user_id !== user.id).slice(0, 8));
            } else {
                setMyLists([]);
                setCommunityLists(publicData.slice(0, 8));
            }
        } catch (error) {
            console.error("Error al cargar listas:", error);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        window.scrollTo(0, 0);
        fetchAllLists();
    }, [user]);

    
    const handleDeleteList = async (id) => {
        if (!window.confirm("¿Seguro que quieres borrar esta lista?")) return;
        try {
            await listService.deleteList(id);
            fetchAllLists(); 
        } catch (err) {
            alert("No se pudo borrar");
        }
    };

    if (loading) return <LoadingAnimation mensaje="Cargando listas..." />;

    return (
        <div className="lists-page-container">
            {/* HERO SECTION AL ESTILO MOVIESPAGE */}
            <section className="lists-hero">
                <h1>Explora las Colecciones</h1>
                <p>Descubre y crea listas épicas con la comunidad de LamerBox.</p>
            </section>

        {user && (
            <section className="lists-section">
                <h2 className="section-title">Tus Listas</h2>
                <div className="lists-grid">
                    <ListCard isCreateCard={true} />
                    {myLists.map(list => (
                        <ListCard 
                            key={list.id} 
                            list={list} 
                            onDelete={handleDeleteList} 
                            showActions={true} 
                        />
                    ))}
                </div>
            </section>
        )}

            <section className="lists-section">
                <h2 className="section-title">Listas de la comunidad</h2>
                <div className="lists-grid">
                    {communityLists.map(list => (
                        <ListCard 
                            key={list.id} 
                            list={list} 
                            showActions={false} // Las de otros NO tienen botones
                        />
                    ))}
                </div>
            </section>

            <section className="lists-section">
                <h2 className="section-title">Sugerencias de LamerBox</h2>
                <div className="api-suggested-grid">
                    {suggestedLists.map(list => (
                        <div key={list.id} className="api-stack-card" onClick={() => navigate(`/search?q=${list.query}`)}>
                            <div className="list-stack">
                                <div className="stack-layer layer-3" style={{ backgroundImage: `url(${list.posters?.[2]})` }}></div>
                                <div className="stack-layer layer-2" style={{ backgroundImage: `url(${list.posters?.[1]})` }}></div>
                                <div className="list-poster-main" style={{ backgroundImage: `url(${list.posters?.[0]})` }}>
                                    <div className="stack-overlay"><span>VER MÁS</span></div>
                                </div>
                            </div>
                            <div className="api-stack-info">
                                <h3>{list.name}</h3>
                                <p>{list.desc}</p>
                            </div>
                        </div>
                    ))}
                </div>
            </section>
        </div>

    );
};

export default ListsPage;