import React, { useEffect, useState } from 'react';
import { listService } from '../services/listService';
import { useAuth } from '../auth/authContext';
import LoadingAnimation from '../components/LoadingAnimation';
import ListCard from '../components/ListCard'; 
import './ListsPage.css';
import { useNavigate } from 'react-router-dom';

const ListsPage = () => {
    const { user } = useAuth();
    const navigate = useNavigate();
    const [communityLists, setCommunityLists] = useState([]);
    const [myLists, setMyLists] = useState([]);
    const [suggestedLists, setSuggestedLists] = useState([]); 
    const [loading, setLoading] = useState(true);

    const fetchAllLists = async () => {
        setLoading(true);
        try {
            const promises = [
                listService.getAllPublicLists(),
                listService.getAutoGeneratedLists()
            ];

            if (user) {
                promises.push(listService.getUserLists());
            }

            const results = await Promise.all(promises);
            const publicData = results[0] || [];
            const autoData = results[1] || [];
            const userData = results[2] || [];

            setSuggestedLists(autoData);

            if (user) {
                setMyLists(userData);
                setCommunityLists(publicData.filter(l => l.user_id !== user.id).slice(0, 8));
            } else {
                setMyLists([]);
                setCommunityLists(publicData.slice(0, 9));
            }
        } catch (error) {
            console.error("Error al cargar listas:", error);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        window.scrollTo(0, 0);
        fetchAllLists();
    }, [user]);

    const handleDeleteList = async (id) => {
        if (!window.confirm("¿Seguro que quieres borrar esta lista?")) return;
        try {
            await listService.deleteList(id);
            fetchAllLists(); 
        } catch (err) {
            alert("No se pudo borrar");
        }
    };

    if (loading) return <LoadingAnimation mensaje="Cargando listas..." />;

    return (
        <div className="lists-page-container">
            <section className="lists-hero">
                <h1>Explora las Colecciones</h1>
                <p>Descubre y crea listas épicas con la comunidad de LamerBox.</p>
            </section>

            {user && (
                <section className="lists-section">
                    <h2 className="section-title">Tus Listas</h2>
                    <div className="lists-grid">
                        <ListCard isCreateCard={true} />
                        {myLists.map(list => (
                            <ListCard key={list.id} list={list} onDelete={handleDeleteList} showActions={true} />
                        ))}
                    </div>
                </section>
            )}

            <section className="lists-section">
                <h2 className="section-title">Listas de la comunidad</h2>
                <div className="lists-grid">
                    {communityLists.map(list => (
                        <ListCard key={list.id} list={list} showActions={false} />
                    ))}
                </div>
            </section>

          <section className="lists-section suggested-section">
                <h2 className="section-title">Sugerencias de LamerBox</h2>
                <div className="featured-list-group">
                    {suggestedLists.map(list => (
                        <div 
                            key={list.id} 
                            className="featured-list-card" 
                            onClick={() => navigate(`/search?q=${list.query}`)} 
                        >
                            <div className="poster-stack">
                                {list.posters.map((url, index) => (
                                    <img 
                                        key={index} 
                                        src={url} 
                                        alt="poster" 
                                        className={`stack-poster poster-${index}`} 
                                    />
                                ))}
                            </div>
                            <div className="list-content">
                                <h3 className="list-title">{list.name}</h3>
                                <div className="list-metadata">
                                    <span>{list.movieCount} películas</span> 
                                </div>
                                <p className="list-description">{list.desc}</p>
                            </div>
                        </div>
                    ))}
                </div>
            </section>
        </div>
    );
};

export default ListsPage;